/* eslint-disable prettier/prettier */
export const users = [
  {
    firstName: "Logan",
    lastName: "Howlett",
    email: "logan.howlett@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/logan.howlett.png",
    active: true,
  },
  {
    firstName: "Wade",
    lastName: "Wilson",
    email: "wade.wilson@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/wade.wilson.png",
    active: true,
  },
  {
    firstName: "Steve",
    lastName: "Rogers",
    email: "steve.rogers@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/steve.rogers.png",
    active: true,
  },
  {
    firstName: "James",
    lastName: "Novello",
    email: "james.novello@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/user4.png",
    active: true,
  },
  {
    firstName: "Peter",
    lastName: "Parker",
    email: "peter.parker@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/peter.parker.png",
    active: true,
  },
  {
    firstName: "Tony",
    lastName: "Stark",
    email: "tony.stark@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/tony.stark.png",
    active: true,
  },
  {
    firstName: "Wanda",
    lastName: "Maximoff",
    email: "wanda.maximoff@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/wanda.maximoff.png",
    active: true,
  },
  {
    firstName: "Natasha",
    lastName: "Romanoff",
    email: "natasha.romanoff@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/natasha.romanoff.png",
    active: true,
  },
  {
    firstName: "Carol",
    lastName: "Danvers",
    email: "carol.danvers@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/carol.danvers.png",
    active: true,
  },
  {
    firstName: "Jennifer",
    lastName: "Walters",
    email: "jennifer.walters@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/jennifer.walters.png",
    active: true,
  },
  {
    firstName: "Kate",
    lastName: "Bishop",
    email: "kate.bishop@mail.com",
    password: "password",
    role: "user",
    avatar: "/avatars/kate.bishop.png",
    active: true,
  },
  {
    firstName: "Nick",
    lastName: "Fury",
    email: "nick.fury@mail.com",
    password: "password",
    role: "admin",
    avatar: "/avatars/nick.fury.png",
    active: true,
  },
];
